### ISSUE TITLE
请支持增加一个选项来使用外部地区数据

### ISSUE THREAD

**Issue by wongyouth** [saberma/china_city#12]
我写了一个 https://github.com/wongyouth/chinacity 用来从统计局官网取得最新的地区数据。

通过对比发现`china_city`的 `areas.json` 地区数据不是最新的，原本想递交PR，更新下最新数据。但是这样就可能导致已经在使用的Rails应用的数据关联失效。

所以是否能增加一个option来指定一个外部数据文件而不是`china_city`附带的地区数据。

**Comment by saberma** [comment]
0.0.5 已经更新到最新的国标了，数据就是来自于统计局官网。

**Comment by wongyouth** [comment]
最近发现统计局的数据还不是最新的，民政部的统计数据才是 http://www.mca.gov.cn/article/sj/tjbz/a/2015/
