### ISSUE TITLE
每个城市下面都有一个「市辖区」

### ISSUE THREAD

**Issue by ybian** [saberma/china_city#13]
我发现在选择了省份、城市以后，区域选择中总是有一个「市辖区」。这个是设计吗？好像不符合习惯啊，比如我在淘宝编辑收获地址的时候就没有「市辖区」的选项。

**Comment by saberma** [comment]
市辖区是在国际那里来的：
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html

不确定是否能够去掉。
