### ISSUE TITLE
是否可增加街道信息

### ISSUE THREAD

**Issue by guxiaobai** [saberma/china_city#18]
淘宝最新收获地址增加了街道选项
![_yk p2z _ ynh4j3j2bjj8](https://cloud.githubusercontent.com/assets/5622315/7290829/4f44d1d0-e9b8-11e4-8555-c62c6c10a922.png)

**Comment by saberma** [comment]
0.0.5 版本增加了街道了。

https://rubygems.org/gems/china_city
