### ISSUE TITLE
To update datasource：db/areas.json

### ISSUE THREAD

**Issue by xufeiyun** [saberma/china_city#22]
非常好的一个插件。

不过，目前来看，数据方面需要做一次更新了。
比如一些城市的区域已经划分的更多了，(可能行政区域上并没有划分开来)，如果也能加进来做选择就更妥了。
如深圳共十二个区政府(包括市辖区)：
原六个区：福田区，罗湖区，南山区，盐田区，龙岗区，宝安区
后新增四个区：光明新区，坪山新区，龙华新区，大鹏新区
但好像又还有一个最近的：前海
http://www.baoan.gov.cn/， 下面有一个各区政府说明。

**Comment by xufeiyun** [comment]
据未证实的官方统计，新代码如下：
 大鹏新区 440312  龙华新区 440311  光明新区 440310   坪山新区 440311

**Comment by saberma** [comment]
0.0.5 版本已经更新到最新的国标数据。
https://rubygems.org/gems/china_city

**Comment by saberma** [comment]
深圳的几个新增加的还没有进入国标中，看来只能额外加入了。
