### ISSUE TITLE
修改省份后，之前的选择城市还保留在选择列表里面

### ISSUE THREAD

**Issue by bingxie** [saberma/china_city#26]
就是 #25 这个问题还是存在。

**Comment by saberma** [comment]
是在哪个浏览器下出现的问题呢？我试着重现一下。

**Comment by bingxie** [comment]
我是用的chrome浏览器。

**Comment by saberma** [comment]
我创建了个示例代码 https://github.com/saberma/china_city_example ，上传到 heroku 试了也是正常的。
http://g.recordit.co/offzbw8BVj.gif

你试下 http://china-city-example.herokuapp.com/ 能不能重现问题？

**Comment by bingxie** [comment]
你提供的这个实例是没有问题。现在支持4级选择，更新过版本吗？

**Comment by saberma45** [comment]
v0.0.5 以上支持 4 级联动了。
